import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import { Sidebar } from 'lucide-react';

const open_sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={open_sans.className}>
        <div className='flex flex-col min-h-screen'>
          <Navbar />
          <div className='flex flex-1'>
            <Sidebar />
            <main className='flex-1 p-4'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
